### ISSUE TITLE
Azure python tasks use 'python'

### ISSUE THREAD

**Issue by st0ve** [Food-X-Technologies/devops-agent#14]
Python tasks in devops pipelines will use 'python' by default, however it looks like the PATH variable to the python executable is defined as 'python3', which causes the python tasks to fail

**Comment by gnadaban** [comment]
As a quickfix, you can specify the `pythonInterpreter` for the `PythonScript@0` task like so:

```yaml
- task: PythonScript@0
  displayName: 'Run Data Deploy Script'
  pythonInterpreter:  '/usr/bin/python2'
  inputs:
    scriptSource: filePath
    scriptPath: scripts/${{ parameters.script_name }}.py
  ...
```

For Python3:
```yaml
- task: PythonScript@0
  displayName: 'Run Data Deploy Script'
  pythonInterpreter:  '/usr/bin/python3'
  inputs:
    scriptSource: filePath
    scriptPath: scripts/${{ parameters.script_name }}.py
  ...
```
